# This file was generated by GoReleaser. DO NOT EDIT.
cask "chroncal" do
  version "0.3.4"

  on_macos do
    on_intel do
      sha256 "9057227f5fa6b89c430b64e8ae798769b673ea3e0c06a45ded3009e22fd21db7"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b134bc726dea592cdb87d91bda3a7aeab16f027ad47b194f50cb5d3ad04d67eb"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "70affc083f559bff1109d582cd0dfc7f5aba227a5d440f04b4f4702dfaa6bd70"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cd607ebf92537bb2df94552644a05531c10935d08788eb5f1f60f45d3152bb9"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chroncal"
  desc "Terminal-first calendar, todo, and journal manager"
  homepage "https://github.com/DouglasdeMoura/chroncal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chroncal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chroncal"]
    end
  end

  # No zap stanza required

end
