# This file was generated by GoReleaser. DO NOT EDIT.
cask "chroncal" do
  postflight_steps do
    on_macos do
      run "/bin/sh", args: ["-c", <<~'SH', "sh", "{{staged_path}}/chroncal"]
        names=$(/usr/bin/xattr "$1") || exit
        printf '%s\n' "$names" | /usr/bin/grep -qxF com.apple.quarantine || exit 0
        exec /usr/bin/xattr -d com.apple.quarantine "$1"
      SH
    end
  end

  version "0.12.2"

  on_macos do
    on_arm do
      sha256 "8b14b77ddca20e06d9f4a348150a2c858a8a337df633779e81d406d73a64953e"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "60ddbdeeaaf0b05d6697a2693c76715e1c04d7187b882a4208b544f492242f5b"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3745e1e157306f22c857bc0fe10bf00fe88d8ce699e16d3f149eb2d5fc19006"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa87c5377993ed6ab329d4b69eb633d9e2563265b87dd010be0a3dde3d60d544"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chroncal"
  desc "Terminal-first calendar, todo, and journal manager"
  homepage "https://github.com/DouglasdeMoura/chroncal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chroncal"

  # No zap stanza required
end
