# This file was generated by GoReleaser. DO NOT EDIT.
cask "chroncal" do
  version "0.7.12"

  on_macos do
    on_intel do
      sha256 "126a844fd486e3bea07667fb7c37be093eeeba8264b488cee206250524e6afa8"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f21ffd6a7ea5e7c74ba5be1ee37926e8b489046c9f5d762ffe14972e8a8e425f"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "60e86b2daba530a5caba74adb5c01f4313b6296a7147f4b8adfcc9d805a80366"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bea68d96731ff41795fec0d8915f480cc5d0cb1877fec9903e3bdd3149faa52"
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v#{version}/chroncal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chroncal"
  desc "Terminal-first calendar, todo, and journal manager"
  homepage "https://github.com/DouglasdeMoura/chroncal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chroncal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chroncal"]
    end
  end

  # No zap stanza required

end
