# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chroncal < Formula
  desc "Terminal-first calendar, todo, and journal manager"
  homepage "https://github.com/DouglasdeMoura/chroncal"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v0.2.4/chroncal_0.2.4_darwin_amd64.tar.gz"
      sha256 "faec74bc326e9895347fc6229c9f616ec8d7689bd55b6cc3abacc6ff7097d4dd"

      define_method(:install) do
        bin.install "chroncal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v0.2.4/chroncal_0.2.4_darwin_arm64.tar.gz"
      sha256 "0c8291d539f78472ca014f1ec597f4df665ceffea8ee99d5855b06ff03901102"

      define_method(:install) do
        bin.install "chroncal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v0.2.4/chroncal_0.2.4_linux_amd64.tar.gz"
      sha256 "41eb686e3e218333d7f1512b9e5ecd672e43f2af89a1543684ff15d868a06ead"
      define_method(:install) do
        bin.install "chroncal"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v0.2.4/chroncal_0.2.4_linux_armv6.tar.gz"
      sha256 "34250faeec26d176331c42a8fa363bbfe8a44ebe9cea9d59e36210653cf0e573"
      define_method(:install) do
        bin.install "chroncal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v0.2.4/chroncal_0.2.4_linux_arm64.tar.gz"
      sha256 "9bf7f0dc0bd3971c6af26c1d96843544907f48af29ce3ff877de25f135d3ea0a"
      define_method(:install) do
        bin.install "chroncal"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/chroncal --version")
  end
end
