# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chroncal < Formula
  desc "Terminal-first calendar, todo, and journal manager"
  homepage "https://github.com/DouglasdeMoura/chroncal"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v0.2.4/chroncal_0.2.4_darwin_amd64.tar.gz"
      sha256 "22bfc4d6a0d7a4376b60da8bd951e9671b396b036c1081499ad88d9d74b90305"

      define_method(:install) do
        bin.install "chroncal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v0.2.4/chroncal_0.2.4_darwin_arm64.tar.gz"
      sha256 "d75c2c56623fada23d24b87d94bfb4d8e4d5df80f1e8720bb2f3af8e0dc41d98"

      define_method(:install) do
        bin.install "chroncal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v0.2.4/chroncal_0.2.4_linux_amd64.tar.gz"
      sha256 "f8fb099fd5a0d260c1c57e2ced1cb24181a04e816d57aaa9b5c6851a523cfc79"
      define_method(:install) do
        bin.install "chroncal"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v0.2.4/chroncal_0.2.4_linux_armv6.tar.gz"
      sha256 "4a62f78d22b4f68e45525dadaf70d044639947a2a87c088e31fbf3b9df2b24bd"
      define_method(:install) do
        bin.install "chroncal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DouglasdeMoura/chroncal/releases/download/v0.2.4/chroncal_0.2.4_linux_arm64.tar.gz"
      sha256 "734d1e9d20ec377b850f45585aab829b5982be7e793321c7c0515957d1871155"
      define_method(:install) do
        bin.install "chroncal"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/chroncal --version")
  end
end
